export const FIREBASE_LISTEN_REQUESTED = 'FIREBASE_LISTEN_REQUESTED';
export const FIREBASE_LISTEN_FULFILLED = 'FIREBASE_LISTEN_FULFILLED';
export const FIREBASE_LISTEN_REJECTED = 'FIREBASE_LISTEN_REJECTED';
export const FIREBASE_LISTEN_REMOVED = 'FIREBASE_LISTEN_REMOVED';
export const FIREBASE_LISTEN_CHILD_ADDED = 'FIREBASE_LISTEN_CHILD_ADDED';
export const FIREBASE_LISTEN_CHILD_CHANGED = 'FIREBASE_LISTEN_CHILD_CHANGED';
export const FIREBASE_LISTEN_CHILD_REMOVED = 'FIREBASE_LISTEN_CHILD_REMOVED';

export const FIRESTORE_LISTEN_REQUESTED = 'FIRESTORE_LISTEN_REQUESTED';
export const FIRESTORE_LISTEN_FULFILLED = 'FIRESTORE_LISTEN_FULFILLED';
export const FIRESTORE_LISTEN_REJECTED = 'FIRESTORE_LISTEN_REJECTED';
export const FIRESTORE_LISTEN_REMOVED = 'FIRESTORE_LISTEN_REMOVED';
export const FIRESTORE_LISTEN_DOC_ADDED = 'FIRESTORE_LISTEN_DOC_ADDED';
export const FIRESTORE_LISTEN_DOC_CHANGED = 'FIRESTORE_LISTEN_DOC_CHANGED';
export const FIRESTORE_LISTEN_DOC_REMOVED = 'FIRESTORE_LISTEN_DOC_REMOVED';