// *** DOMAIN ACTIONS *** //
export const REQUEST_ACTIVITIES = 'REQUESTED_ACTIVITIES';
export const FETCH_ACTIVITIES = 'ADD_ACTIVITIES';
export const REJECT_ACTIVITIES = 'REJECT_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';

export const REQUEST_ACTIVITY_ATTEMPTS = 'REQUEST_ACTIVITY_ATTEMPTS';
export const FETCH_ACTIVITY_ATTEMPTS = 'FETCH_ACTIVITY_ATTEMPTS';
export const REJECT_ACTIVITY_ATTEMPTS = 'REJECT_ACTIVITY_ATTEMPTS';
export const ADD_ACTIVITY_ATTEMPT = 'ADD_ACTIVITY_ATTEMPT';
export const UPDATE_ACTIVITY_ATTEMPT = 'UPDATE_ACTIVITY_ATTEMPT';
export const REMOVE_ACTIVITY_ATTEMPT = 'REMOVE_ACTIVITY_ATTEMPT';

// export const STUDY_SHOW_ACTIVITIES = 'STUDY_SHOW_ACTIVITIES';
// export const STUDY_SEARCH_ACTIVITIES = 'STUDY_SEARCH_ACTIVITIES';
// export const STUDY_SUGGEST_ACTIVITIES = 'STUDY_SUGGEST_ACTIVITIES';
// *** APP ACTIONS *** //
export const STUDY_SELECT_ACTIVITY = 'STUDY_SELECT_ACTIVITY';
export const STUDY_NEXT_ACTIVITY = 'STUDY_NEXT_ACTIVITY';
export const STUDY_PREVIOUS_ACTIVITY = 'STUDY_PREVIOUS_ACTIVITY';

export const STUDY_LOAD_ACTIVITY_ATTEMPT = 'STUDY_LOAD_ACTIVITY_ATTEMPT';
export const STUDY_DO_ACTIVITY_ATTEMPT = 'STUDY_DO_ACTIVITY_ATTEMPT';
export const STUDY_PAUSE_ACTIVITY_ATTEMPT = 'STUDY_PAUSE_ACTIVITY_ATTEMPT';
export const STUDY_REDO_ACTIVITY_ATTEMPT = 'STUDY_REDO_ACTIVITY_ATTEMPT';
export const STUDY_FINISH_ACTIVITY_ATTEMPT = 'STUDY_FINISH_ACTIVITY_ATTEMPT';
export const STUDY_EXIT_ACTIVITY_ATTEMPT = 'STUDY_EXIT_ACTIVITY_ATTEMPT';

export const STUDY_LIKE_ACTIVITY = 'STUDY_LIKE_ATIVITY';
export const STUDY_RATING_ACTIVITY = 'STUDY_RATING_ACTIVITY';

export const ACTIVITY_ATTEMPT_STATUS = {
    Pending: 'Pending',
    InProgress: 'InProgress',
    Pause: 'Pause',
    Complete: 'Complete',
}