export const DOMAIN_DO_ACTION = 'DOMAIN_DO_ACTION';
export const DOMAIN_NOTIFY_ERROR = 'DOMAIN_NOTIFY_ERROR';

export const DOMAIN_ADD_ITEM = 'DOMAIN_ADD_ITEM';
export const DOMAIN_MODIFY_ITEM = 'DOMAIN_MODIFY_ITEM';
export const DOMAIN_REMOVE_ITEM = 'DOMAIN_REMOVE_ITEM';
export const DOMAIN_ADD_ITEMS = 'DOMAIN_ADD_ITEMS';
export const DOMAIN_MODIFY_ITEMS = 'DOMAIN_MODIFY_ITEMS';
export const DOMAIN_REMOVE_ITEMS = 'DOMAIN_REMOVE_ITEMS';

export const DOMAIN_CLEAR_ITEMS = 'DOMAIN_CLEAR_ITEMS';